import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { ModeToggle } from "@/components/shared/ModeToggle";
import Hydrations from "@/components/shared/Hydrations";
import GlobalAlerts from "@/components/shared/GlobalAlerts";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/AppSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
            <Header />
            <Hydrations />
            <div className="flex-1 flex flex-col">
              <SidebarProvider>
                {children}
              </SidebarProvider>
              <GlobalAlerts /> 
            </div>
            <div className="fixed bottom-4 right-4 z-50">
              <ModeToggle />
            </div>
            <Footer/>
          </ThemeProvider>
      </body>
    </html>
  );
}
